### ISSUE TITLE
win10 64位下安装失败

### ISSUE THREAD

**Issue by pjwok** [alex8088/clipboard-files#12]
node 版本 `v14.18.1`
npm 版本  `6.14.15`

执行的命令
`npm i clipboard-files --build-from-source --runtime=electron --target=19.0.4 --target_arch=x64 --dist-url=https://atom.io/download/electron`

错误提示
```bash
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 403 response downloading https://atom.io/download/electron/v19.0.4/node-v19.0.4-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (D:\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:188:14)
gyp ERR! stack     at Request.emit (events.js:412:35)
gyp ERR! stack     at Request.onRequestResponse (D:\nodejs\node_modules\npm\node_modules\request\request.js:1066:10)
gyp ERR! stack     at ClientRequest.emit (events.js:400:28)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:515:22)
gyp ERR! stack     at TLSSocket.emit (events.js:400:28)
gyp ERR! stack     at addChunk (internal/streams/readable.js:293:12)
gyp ERR! stack     at readableAddChunk (internal/streams/readable.js:267:9)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=E:\\mydesktop\\images\\node_modules\\clipboard-files\\lib\\binding\\electron-v19.0-win32-x64\\binding.node" "--module_name=binding" "--module_path=E:\\mydesktop\\images\\node_modules\\clipboard-files\\lib\\binding\\electron-v19.0-win32-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v19.0" "--dist-url=https://atom.io/download/electron"
gyp ERR! cwd E:\mydesktop\images\node_modules\clipboard-files
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'D:\nodejs\node.exe D:\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\mydesktop\images\node_modules\clipboard-files\lib\binding\electron-v19.0-win32-x64\binding.node --module_name=binding --module_path=E:\mydesktop\images\node_modules\clipboard-files\lib\binding\electron-v19.0-win32-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v19.0 --dist-url=https://atom.io/download/electron' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\mydesktop\images\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
node-pre-gyp ERR! System Windows_NT 10.0.19044
node-pre-gyp ERR! command "D:\\nodejs\\node.exe" "E:\\mydesktop\\images\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\mydesktop\images\node_modules\clipboard-files
node-pre-gyp ERR! node -v v14.18.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.9
node-pre-gyp ERR! not ok
Failed to execute 'D:\nodejs\node.exe D:\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\mydesktop\images\node_modules\clipboard-files\lib\binding\electron-v19.0-win32-x64\binding.node --module_name=binding --module_path=E:\mydesktop\images\node_modules\clipboard-files\lib\binding\electron-v19.0-win32-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v19.0 --dist-url=https://atom.io/download/electron' (1)
npm WARN images@1.0.0 No description
npm WARN images@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! clipboard-files@1.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the clipboard-files@1.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2022-06-17T10_25_35_556Z-debug.log```

**Comment by pjwok** [comment]
更新visual studio后，可以安装
